version: '2'

services:

  # Web page rendering service, rendering live web pages:
  webrender:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    environment: # DOCKER_HOST could be used to run rendering on a dedicated service.
      - "DOCKER_NETWORK=webrender-api_default" # warcprox network, to attach renderer containers to
      - "LC_ALL=en_US.utf8"
      - "WEB_RENDER_TMP=/tmp/webrender" # Has to match the _host_ folder mounted below.
      - "DOCKER_RENDERER_IMAGE=ukwa/webrender-puppeteer:1.0.10"
      #- "WARCPROX=warcprox:8000" # Use WARCPROX so that interactions are archived.
      - "HTTP_PROXY=explorer.bl.uk:3127"
      - "HTTPS_PROXY=explorer.bl.uk:3127"
    ports:
      - "8010:8010"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Needs to connect to Docker to launch render container
      - /tmp/webrender:/tmp/webrender # Host mount must match internal mount at present!

  # WARC Proxy, with de-duplication disabled and a rapid rollover:
  warcprox:
    image: ukwa/warcprox:2.4.17
    command: "warcprox -b 0.0.0.0 -d /heritrix/wren --base32 --gzip --rollover-idle-time 600 --dedup-db-file /dev/null --stats-db-file /dev/null --quiet --plugin warcprox-plugins.listeners.UpdateOutbackCDX"
    environment:
      - "LC_ALL=en_US.utf8"
      - "TMP=/tmp/warcprox"
      - "CDXSERVER_ENDPOINT=http://cdxserver:8080/fc"
    #ports:
    #  - "8000:8000"
    volumes:
      - "./output:/heritrix/wren"

  # tinycdxserver
  cdxserver:
    image: nlagovau/outbackcdx:0.7.0
    # Verbose form logs submissions:
    #command: "java -jar outbackcdx.jar -v -d /cdx-data -p 8080 -b 0.0.0.0"
    ports:
      - "7070:8080"

  # 
  # IIIF Server to manipulate images
  # Reference for env vars: https://github.com/lyrasis/docker-cantaloupe/blob/master/Dockerfile
  # 
  iiif:
    image: lyrasis/cantaloupe
    environment:
      SOURCE_STATIC: "HttpSource"
      HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_PREFIX: "http://webrender:8010/render?show_screenshot=true&url="
      HTTPSOURCE_BASICLOOKUPSTRATEGY_URL_SUFFIX: ""
      HTTPSOURCE_REQUEST_TIMEOUT: 3600
      PROCESSOR_STREAM_RETRIEVAL_STRATEGY: "CacheStrategy"
      # Seems to cope better with sharp edges:
      PROCESSOR_DOWNSCALE_FILTER: "Lanczos3"
      # Web pages suffer badly from JPEG artefacts. Can use PNG instead.
      PROCESSOR_JPG_QUALITY: 100 
      ENDPOINT_ADMIN_ENABLED: "true"
      LOG_APPLICATION_LEVEL: "warn"
      LOG_ACCESS_CONSOLEAPPENDER_ENABLED: "true"
    ports:
      - 8182:8182
    volumes:
      - ./cache:/var/cache/cantaloupe

